version: '1'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cu2gether_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_CU_WEB=${NEXT_PUBLIC_CU_WEB:-http://localhost:3000/}
      - NEXT_PUBLIC_CU_API=${NEXT_PUBLIC_CU_API:-http://localhost:3001/}
    restart: always
