name: Automated testing for merging 

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    name: Automated testing!
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Push
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          REPO: main
          TAG_NAME: cu2gether
        run: |
          docker build -t $REPO:$TAG_NAME .
          docker tag $REPO:$TAG_NAME $DOCKER_USER/$REPO:$TAG_NAME
          docker push $DOCKER_USER/$REPO:$TAG_NAME  
      - name: Docker Pull and Run
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          REPO: main
          TAG_NAME: cu2gether
          EC2_USER: ${{secrets.EC2_USER}}
          EC2_PUBLIC_DNS: ${{secrets.EC2_PUBLIC_DNS}}
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_PUBLIC_DNS
          sudo docker pull $DOCKER_USER/$REPO:$TAG_NAME
          sudo docker run -p 3000:3000 $DOCKER_USER/$REPO:$TAG_NAME